import datetime

simplemessages = [{'attachments': [{'filename': 'unknown.png',
                                    'id': 770583153134796800,
                                    'message_id': 10,
                                    'url': 'https://picsum.photos/400/300.jpg'}],
                   'found_via': 'pinned',
                   'id': 10,
                   'sender_avatar': 'https://picsum.photos/seed/mitch/512.jpg',
                   'sender_id': 402326044872409100,
                   'sender_name': 'GiantPredatoryMollusk',
                   'text': '',
                   'time': datetime.datetime(2020, 10, 27, 9, 42, 20, 497000)},
                  {'attachments': [],
                   'found_via': 'pinned',
                   'id': 11,
                   'sender_avatar': 'https://picsum.photos/seed/cassie/512.jpg',
                   'sender_id': 338261686014181377,
                   'sender_name': 'Cassie',
                   'text': 'u have no idea how much I mean to me',
                   'time': datetime.datetime(2020, 10, 24, 6, 13, 44, 957000)},
                  {'attachments': [],
                   'found_via': 'pinned',
                   'id': 12,
                   'sender_avatar': 'https://picsum.photos/seed/cassie/512.jpg',
                   'sender_id': 338261686014181377,
                   'sender_name': 'Cassie',
                   'text': "I did rocking horse and they were just like 'fucking a horse'???",
                   'time': datetime.datetime(2020, 10, 24, 6, 0, 17, 424000)},
                  {'attachments': [],
                   'found_via': 'pinned',
                   'id': 13,
                   'sender_avatar': 'https://picsum.photos/seed/cassie/512.jpg',
                   'sender_id': 338261686014181377,
                   'sender_name': 'Cassie',
                   'text': "I'm Too Drink for charades ??????????",
                   'time': datetime.datetime(2020, 10, 24, 5, 59, 59, 874000)}]

avatarchange = [{'attachments': [],
                 'found_via': 'pinned',
                 'id': 14,
                 'sender_avatar': 'https://picsum.photos/seed/cassie2/512.jpg',
                 'sender_id': 338261686014181377,
                 'sender_name': 'Cassie',
                 'text': 'new avatar',
                 'time': datetime.datetime(2020, 11, 5, 7, 0, 17, 424000)},
                {'attachments': [],
                 'found_via': 'pinned',
                 'id': 16,
                 'sender_avatar': 'https://picsum.photos/seed/mitch/512.jpg',
                 'sender_id': 402326044872409100,
                 'sender_name': 'GiantPredatoryMollusk',
                 'text': 'another normal message (old avatar and username)',
                 'time': datetime.datetime(2020, 11, 5, 8, 42, 20, 497000)},
                {'attachments': [],
                 'found_via': 'pinned',
                 'id': 15,
                 'sender_avatar': 'https://picsum.photos/seed/cassie2/512.jpg',
                 'sender_id': 338261686014181377,
                 'sender_name': 'Cassie',
                 'text': 'normal message (new avatar)',
                 'time': datetime.datetime(2020, 11, 5, 8, 50, 17, 424000)}]

avatarandusernamechange = [{'attachments': [],
                            'found_via': 'pinned',
                            'id': 17,
                            'sender_avatar': 'https://picsum.photos/seed/mitch2/512.jpg',
                            'sender_id': 402326044872409100,
                            'sender_name': 'SmolPredatoryMollusk',
                            'text': 'avatar and username change',
                            'time': datetime.datetime(2020, 11, 5, 9, 42, 20, 497000)},
                           {'attachments': [],
                            'found_via': 'pinned',
                            'id': 18,
                            'sender_avatar': 'https://picsum.photos/seed/cassie2/512.jpg',
                            'sender_id': 338261686014181377,
                            'sender_name': 'Cassie',
                            'text': 'normal message (still new avatar)',
                            'time': datetime.datetime(2020, 11, 5, 10, 0, 17, 424000)},
                           {'attachments': [{'filename': 'dan.gif',
                                             'id': 773681339043020830,
                                             'message_id': 19,
                                             'url': 'https://picsum.photos/400/300.jpg'}],
                            'found_via': 'pinned',
                            'id': 19,
                            'sender_avatar': 'https://picsum.photos/seed/mitch2/512.jpg',
                            'sender_id': 402326044872409100,
                            'sender_name': 'SmolPredatoryMollusk',
                            'text': 'attachment message',
                            'time': datetime.datetime(2020, 11, 6, 9, 42, 20, 497000)}]

oldmessages = [{'attachments': [],
                'found_via': 'deep search',
                'id': 5,
                'sender_avatar': 'https://picsum.photos/seed/mitch/512.jpg',
                'sender_id': 402326044872409100,
                'sender_name': 'GiantPredatoryMollusk',
                'text': 'unpinned thing',
                'time': datetime.datetime(2020, 11, 5, 11, 42, 20, 497000)},
               {'attachments': [{'filename': 'url1.jpg',
                                 'id': 772743393788428298,
                                 'message_id': 6,
                                 'url': 'https://picsum.photos/400/300.jpg'},
                                {'filename': 'url2.jpg',
                                 'id': 772743393788428299,
                                 'message_id': 6,
                                 'url': 'https://picsum.photos/400/300.jpg'}],
                'found_via': 'deep search',
                'id': 6,
                'sender_avatar': 'https://picsum.photos/seed/cassie/512.jpg',
                'sender_id': 338261686014181377,
                'sender_name': 'Cassie',
                'text': 'other unpinned thing',
                'time': datetime.datetime(2020, 11, 5, 11, 43, 17, 424000)}]

specifiedmessages = [{'attachments': [],
                      'found_via': 'provided',
                      'id': 3,
                      'sender_avatar': 'https://picsum.photos/seed/mitch/512.jpg',
                      'sender_id': 402326044872409100,
                      'sender_name': 'GiantPredatoryMollusk',
                      'text': 'message from id',
                      'time': datetime.datetime(2019, 11, 5, 11, 42, 20, 497000)},
                     {'attachments': [{'filename': 'url1.jpg',
                                       'id': 772743393788428100,
                                       'message_id': 6,
                                       'url': 'https://picsum.photos/400/300.jpg'},
                                      {'filename': 'url2.jpg',
                                       'id': 772743393788428101,
                                       'message_id': 6,
                                       'url': 'https://picsum.photos/400/300.jpg'}],
                      'found_via': 'provided',
                      'id': 4,
                      'sender_avatar': 'https://picsum.photos/seed/cassie/512.jpg',
                      'sender_id': 338261686014181377,
                      'sender_name': 'Cassie',
                      'text': 'other message from id',
                      'time': datetime.datetime(2019, 11, 5, 11, 43, 17, 424000)}]
